name: drone_bitbucket_cloud
services:
  drone-server:
    image: drone/drone:2.26.0
    container_name: drone_cloud
    ports:
      - "3001:80"
      - "3002:443"
    restart: always
    volumes:
      - /var/lib/drone:/data
    environment:
      - DRONE_BITBUCKET_CLIENT_ID={drone_bitbucket_client_id}
      - DRONE_BITBUCKET_CLIENT_SECRET={drone_bitbucket_client_secret}
      - DRONE_RPC_SECRET={drone_rpc_secret}
      - DRONE_SERVER_HOST={drone_server_host}
      - DRONE_SERVER_PROTO=https
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_DATADOG_ENABLED=true
      - DRONE_DATABASE_DRIVER=sqlite3
      - XDG_CACHE_HOME=/data

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DRONE_RUNNER_NAME=drone_cloud_runner
      - GODEBUG=netdns=go
      - DRONE_DEBUG=true
      - DRONE_RPC_SECRET={drone_rpc_secret}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_PLATFORM_OS=linux
      - DRONE_PLATFORM_ARCH=amd64
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST={drone_server_host}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.stop-signal: "SIGINT"
      org.opencontainers.image.created: "2025-01-28T22:33:19Z"
      org.opencontainers.image.revision: "9ea626aa421794087058fdea6199257a88c12af8"
      org.opencontainers.image.source: "https://github.com/drone-runners/drone-runner-docker.git"
      org.opencontainers.image.url: "https://github.com/drone-runners/drone-runner-docker"

  bitbucket-cloud-fix:
    image: bitbucket-cloud-pr-drone-fix:latest
    container_name: bitbucket_cloud_fix
    restart: always
    environment:
      - TARGET_URL=http://drone-server:80
      - PROXY_PORT=443
      - USE_HTTPS=true
      - BRANCHES_ALLOWED_PUSH=main,develop
    ports:
      - "443:443"
